[package]
name = "nextjson"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/nextjson"
description.workspace = true
keywords = ["json", "cbor", "serialization", "deserialization", "parser"]
categories = ["encoding", "parser-implementations", "no-std"]
readme = "../README.md"

[features]
default = ["std", "derive"]
std = []
derive = ["dep:nextjson-derive"]

[dependencies]
nextjson-derive = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "format_comparison"
harness = false
